### ISSUE TITLE
多实例问题

### ISSUE THREAD

**Issue by yugonglan** [GoldSubmarine/workflow-bpmn-modeler#28] opened 2020-12-11 08:17 UTC
画多实例节点,并行或串行的标识没有出现,导入其他文件带有多实例节点的,出现一些属性不能回显,下面提供xml文件类容

**Comment by yugonglan** [comment] 2020-12-11 08:17
`<?xml version="1.0" encoding="UTF-8"?>
<definitions xmlns="http://www.omg.org/spec/BPMN/20100524/MODEL" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:flowable="http://flowable.org/bpmn" xmlns:bpmndi="http://www.omg.org/spec/BPMN/20100524/DI" xmlns:omgdc="http://www.omg.org/spec/DD/20100524/DC" xmlns:omgdi="http://www.omg.org/spec/DD/20100524/DI" typeLanguage="http://www.w3.org/2001/XMLSchema" expressionLanguage="http://www.w3.org/1999/XPath" targetNamespace="http://www.flowable.org/processdef">
  <process id="celv" name="策略申请" isExecutable="true">
    <documentation>测试</documentation>
    <startEvent id="startEvent1" name="开始" flowable:formKey="/form/list"></startEvent>
    <userTask id="sid-819AF873-5C60-48AA-B954-0EA03CA5DDA3" name="提交人" flowable:assignee="${initiator}" flowable:skipExpression="${initiator==''}">
      <extensionElements>
        <modeler:initiator-can-complete xmlns:modeler="http://flowable.org/modeler"><![CDATA[false]]></modeler:initiator-can-complete>
      </extensionElements>
    </userTask>
    <sequenceFlow id="sid-00C9DA34-9F53-4710-8AF5-6DCAB65F33F2" sourceRef="startEvent1" targetRef="sid-819AF873-5C60-48AA-B954-0EA03CA5DDA3"></sequenceFlow>
    <userTask id="sid-B9D3F56F-9340-49FB-B776-5F7FE88B50B0" name="部长审批" flowable:assignee="${assign}">
      <extensionElements>
        <modeler:initiator-can-complete xmlns:modeler="http://flowable.org/modeler"><![CDATA[false]]></modeler:initiator-can-complete>
      </extensionElements>
      <multiInstanceLoopCharacteristics isSequential="false" flowable:collection="userList" flowable:elementVariable="assign"></multiInstanceLoopCharacteristics>
    </userTask>
    <sequenceFlow id="sid-254B55A7-E7ED-4B2A-862D-0FBA29D5C744" sourceRef="sid-819AF873-5C60-48AA-B954-0EA03CA5DDA3" targetRef="sid-B9D3F56F-9340-49FB-B776-5F7FE88B50B0"></sequenceFlow>
    <userTask id="sid-D8F6B72A-B774-4C88-9E2F-F8E658C1A97D" name="董事长审批">
      <extensionElements>
        <flowable:taskListener event="create" delegateExpression="${userTaskListener}"></flowable:taskListener>
      </extensionElements>
    </userTask>
    <endEvent id="sid-CB91BB77-BB6B-4B13-B52C-BDE0191DFACA" name="结束"></endEvent>
    <sequenceFlow id="sid-C4853985-0B0A-489B-BCA7-B84A78A5EE17" sourceRef="sid-D8F6B72A-B774-4C88-9E2F-F8E658C1A97D" targetRef="sid-CB91BB77-BB6B-4B13-B52C-BDE0191DFACA"></sequenceFlow>
    <sequenceFlow id="sid-7F461E80-2245-410E-AC27-47D445DE69EC" sourceRef="sid-B9D3F56F-9340-49FB-B776-5F7FE88B50B0" targetRef="sid-D8F6B72A-B774-4C88-9E2F-F8E658C1A97D"></sequenceFlow>
  </process>
  <bpmndi:BPMNDiagram id="BPMNDiagram_celv">
    <bpmndi:BPMNPlane bpmnElement="celv" id="BPMNPlane_celv">
      <bpmndi:BPMNShape bpmnElement="startEvent1" id="BPMNShape_startEvent1">
        <omgdc:Bounds height="30.0" width="30.0" x="100.0" y="163.0"></omgdc:Bounds>
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape bpmnElement="sid-819AF873-5C60-48AA-B954-0EA03CA5DDA3" id="BPMNShape_sid-819AF873-5C60-48AA-B954-0EA03CA5DDA3">
        <omgdc:Bounds height="80.0" width="100.0" x="175.0" y="138.0"></omgdc:Bounds>
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape bpmnElement="sid-B9D3F56F-9340-49FB-B776-5F7FE88B50B0" id="BPMNShape_sid-B9D3F56F-9340-49FB-B776-5F7FE88B50B0">
        <omgdc:Bounds height="80.0" width="100.0" x="320.0" y="138.0"></omgdc:Bounds>
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape bpmnElement="sid-D8F6B72A-B774-4C88-9E2F-F8E658C1A97D" id="BPMNShape_sid-D8F6B72A-B774-4C88-9E2F-F8E658C1A97D">
        <omgdc:Bounds height="80.0" width="100.0" x="465.0" y="138.0"></omgdc:Bounds>
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape bpmnElement="sid-CB91BB77-BB6B-4B13-B52C-BDE0191DFACA" id="BPMNShape_sid-CB91BB77-BB6B-4B13-B52C-BDE0191DFACA">
        <omgdc:Bounds height="28.0" width="28.0" x="610.0" y="164.0"></omgdc:Bounds>
      </bpmndi:BPMNShape>
      <bpmndi:BPMNEdge bpmnElement="sid-00C9DA34-9F53-4710-8AF5-6DCAB65F33F2" id="BPMNEdge_sid-00C9DA34-9F53-4710-8AF5-6DCAB65F33F2">
        <omgdi:waypoint x="129.9499984899576" y="178.0"></omgdi:waypoint>
        <omgdi:waypoint x="174.9999999999917" y="178.0"></omgdi:waypoint>
      </bpmndi:BPMNEdge>
      <bpmndi:BPMNEdge bpmnElement="sid-254B55A7-E7ED-4B2A-862D-0FBA29D5C744" id="BPMNEdge_sid-254B55A7-E7ED-4B2A-862D-0FBA29D5C744">
        <omgdi:waypoint x="274.9499999999907" y="178.0"></omgdi:waypoint>
        <omgdi:waypoint x="319.9999999999807" y="178.0"></omgdi:waypoint>
      </bpmndi:BPMNEdge>
      <bpmndi:BPMNEdge bpmnElement="sid-7F461E80-2245-410E-AC27-47D445DE69EC" id="BPMNEdge_sid-7F461E80-2245-410E-AC27-47D445DE69EC">
        <omgdi:waypoint x="419.94999999999067" y="178.0"></omgdi:waypoint>
        <omgdi:waypoint x="464.9999999999807" y="178.0"></omgdi:waypoint>
      </bpmndi:BPMNEdge>
      <bpmndi:BPMNEdge bpmnElement="sid-C4853985-0B0A-489B-BCA7-B84A78A5EE17" id="BPMNEdge_sid-C4853985-0B0A-489B-BCA7-B84A78A5EE17">
        <omgdi:waypoint x="564.95" y="178.0"></omgdi:waypoint>
        <omgdi:waypoint x="610.0" y="178.0"></omgdi:waypoint>
      </bpmndi:BPMNEdge>
    </bpmndi:BPMNPlane>
  </bpmndi:BPMNDiagram>
</definitions>`

**Comment by GoldSubmarine** [comment] 2020-12-11 08:20
Duplicate of #26

**Closed by GoldSubmarine** 2020-12-11 08:20 UTC
